### ISSUE TITLE
Ch08 Explicit Loading InvalidOperationException

### ISSUE THREAD

**Issue by jyox** [markjprice/cs7dotnetcore#1]
In Chapter 8, in the section implementing explicit loading following the VS 2017 settings, I kept encountering 
`InvalidOperationException Exception: There is already an open DataReader associated with this Command which must be closed first.`
anytime I tried confirming an explicit product load.

Seems to be solved by updating the connection string with MultipleActiveResultSets=True :
`optionsBuilder.UseSqlServer(@"Data Source=(localdb)\mssqllocaldb;Initial Catalog=Northwind;Integrated Security=true;MultipleActiveResultSets=True;"); `

**Comment by markjprice** [comment]
Thank you for spotting this issue, jyox!

I have fixed this in the repo, and I will add an erratum to the book's web site.
