### ISSUE TITLE
Suggestion || Commenting all projects

### ISSUE THREAD

**Issue by danirdd92** [markjprice/cs7dotnetcore#2]
As I'm going through the book I begin to understand that this repo is going to be a valid source of reference in the future. Would that be a possibility to comment everything professionally through a lens of a teacher? Maybe add some bonus insight that is not explicitly covered in the book?

**Comment by markjprice** [comment]
That's a good idea. When I have some free time, I will do that.

**Comment by danirdd92** [comment]
Great! This book is a life changer when it comes to understanding all the concepts of C# and OOP in general. Thank you so much for the effort. Best investment in my life!
